---
title: "Documentos en RMarkdown"
subtitle: "Archivo guía para el uso de RMarkdown en la generación de documentos que incluyan análisis de información, resultados y código en RStudio."
author: "Andres M. Palacio"
output: pdf_document
fig_caption: yes
latex_engine: xelatex
number_sections: yes
toc: yes
date: '\today'
linkcolor: blue
urlcolor: blue
---

\pagebreak

# Introducción a RMarkdown

## Actualización

Para actualizar la librería que utiliza RMarkdown utilizo la siguiente opción:

```{r setup, include = TRUE}
knitr::opts_chunk$set(echo = TRUE)
```

Para la realización de este documento he tomado como fuentes los siguientes enlaces:

* [Rstudio](http://rmarkdown.rstudio.com)

* [Bookdown](https://bookdown.org/gboccardo/manual-ED-UCH/introduccion-al-uso-de-rmarkdown-para-la-compilacion-de-resultados-de-rstudio-en-diferentes-formatos.html)

* [RPubs](https://rpubs.com/tereboca/informe_rmakrdown)

Al hacer clic en el botón **Knit** se generará el documento PDF que está en elaboración.

# Aspectos Generales

## Formato de texto

1.  Ejemplo para utilizar **Negrita**

2.  Ejemplo para utilizar *Cursiva*

3.  Ejemplo para utilizar *Subrayado*

4.  

    > Ejemplo de texto con tabulación

5.  Ejemplo de texto con nota al pie [^1]

[^1]: Texto de la nota al pie

```{=html}
<!-- -->
```
6.  Ejemplo de texto que incluye un hipervínculo: [Manual de R](https://bookdown.org/gboccardo/manual-ED-UCH/introduccion-al-uso-de-rmarkdown-para-la-compilacion-de-resultados-de-rstudio-en-diferentes-formatos.html)

7.  Ejemplo de una lista sin números y con submenú

    -   Elemento 1
    -   Elemento 2

\pagebreak


## Posición del texto


\pagebreak


## Gráficos


\pagebreak


## Tablas

A continuación, un ejemplo de una tabla simple:

Table: Ejemplo de Tabla Simple

   **Título 1** |    **Título 2**
----------------|-----------------
*Texto 1*       | Texto 3
**Texto 2**     | Texto 4

\pagebreak


## Bibliografía


\pagebreak


## Código en R


\pagebreak